# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Rust Toolchain
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "toolchain"
      include: "scope"
    reviewers:
      - "jackchuka"
    assignees:
      - "jackchuka"
    labels:
      - "dependencies"
      - "rust-toolchain"
    target-branch: "main"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "jackchuka"
    assignees:
      - "jackchuka"
    labels:
      - "dependencies"
      - "github-actions"
    target-branch: "main"
